import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../src/components/layout/navbar'
import styles from '../styles/Home.module.css'
import Filters from '../src/components/shared/filters'
import algoliasearch from 'algoliasearch/lite'
import { InstantSearch } from 'react-instantsearch-hooks-web'
import MainSection from '../src/components/JobsBoard/mainSection'
import { Box } from '@chakra-ui/react'


const searchClient = algoliasearch(
  'MVK698T35T',
  '16892df9d986a3976fbf0e13047d6d1b'
)

const Home: NextPage = () => {
  return (
    <Box className={styles.container}>
      <InstantSearch searchClient={searchClient} indexName="jobs">
        <Navbar />
        {/* // <Head>
      //   <title>Create Next App</title>
      //   <meta name="description" content="Generated by create next app" />
      //   <link rel="icon" href="/favicon.ico" />
      // </Head> */}

        <main className={styles.main}>
            <Filters />
            <MainSection />
        </main>
       
      </InstantSearch>
    </Box>
  )
}

export default Home
