import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../src/components/layout/navbar'
import styles from '../styles/Home.module.css'
import MainWrapper from '../src/components/shared/mainWrapper'
import Filters from '../src/components/shared/filters'
import SideBar from '../src/components/layout/sideBar'
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Navbar />
      {/* // <Head>
      //   <title>Create Next App</title>
      //   <meta name="description" content="Generated by create next app" />
      //   <link rel="icon" href="/favicon.ico" />
      // </Head> */}

      <main className={styles.main}>
          <MainWrapper>
            <Filters />
            <div className='flex'>
              <SideBar />
            </div>
          </MainWrapper>
      </main>

    </div>
  )
}

export default Home
